<?php

namespace Tiempo\AdminBundle\Repository;

/**
 * EstadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadosRepository extends \Doctrine\ORM\EntityRepository
{
}
