<?php

namespace Tiempo\AdminBundle\Repository;

/**
 * MarcasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarcasRepository extends \Doctrine\ORM\EntityRepository
{
}
