<?php

namespace Tiempo\AdminBundle\Repository;

/**
 * ProductosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductosRepository extends \Doctrine\ORM\EntityRepository
{
}
